### ISSUE TITLE
Add prettier.config.js file

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend-next#21]
Can be:
```js
module.exports = {
  "arrowParens": "always",
  "bracketSpacing": true,
  "jsxBracketSameLine": false,
  "printWidth": 100,
  "proseWrap": "always",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "all",
  "useTabs": false
};
```

Thoughts @nabeel- ?

**Comment by nabeel-** [comment]
The rules lgtm!

As for the setup, if we want to use prettier as the formatter we'll need to remove the plugin from the `.eslintrc.yml` so we don't have conflicts when it comes to formatting.

The other option would be to add these rules as part of the `.eslintrc.yml`:

```
prettier/prettier:
  - 2
  - arrowParens: always
     bracketSpacing: true
     jsxBracketSameLine: false
     printWidth: 100
     proseWrap: always
     requirePragma: false
     semi: true
     singleQuote: true
     tabWidth: 2
     trailingComma: all
     useTabs: false
```

Do you have a preference one way or the other?
